# numpy.array basic

In [1]:
import numpy

In [2]:
numpy.__version__

'1.17.2'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.17.2'

# feature of list in python

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5]

5

In [7]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [8]:
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

# Python's list does not require store at the same type, cause efficiency probelm to use array

In [9]:
import array
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[5]

5

In [11]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [12]:
arr[5] = "Machine Learning"

TypeError: an integer is required (got type str)

In [13]:
arr[5] = 5.0

TypeError: integer argument expected, got float


# the drawback of array does not see data as vector or matirx, does not support matrix calculation, use np.array

In [14]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [16]:
nparr[5] = "Machine Learning"

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [17]:
nparr.dtype

dtype('int64')

In [18]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
nparr.dtype

dtype('int64')

In [20]:
nparr[5] = 3.14
nparr

array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

In [21]:
nparr2 = np.array([1, 2, 3.0])
nparr2.dtype

dtype('float64')