# 08-Aggregation-Operator-in-Numpy

## sum

In [1]:
import numpy as np

L = np.random.random(100)
sum(L)

46.93496856232112

In [2]:
np.sum(L) # more efficient

46.93496856232111

In [3]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

144 ms ± 8.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
436 µs ± 41.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## min, max

In [4]:
np.min(big_array)

5.374707023886316e-08

In [5]:
np.max(big_array)

0.9999991427901321

In [6]:
big_array.min()

5.374707023886316e-08

In [7]:
big_array.max()

0.9999991427901321

In [8]:
big_array.sum()

500105.11289437045

## sum in high dimension

In [9]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.sum(X)

120

In [11]:
np.sum(X, axis=0) # sum in each column

array([24, 28, 32, 36])

In [12]:
np.sum(X, axis=1) #  sum in each row

array([ 6, 22, 38, 54])

## other sum

In [13]:
np.prod(X) # product

0

In [14]:
np.prod(X + 1) # universal function

20922789888000

In [15]:
np.mean(X)

7.5

In [16]:
np.median(X)

7.5

In [17]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [18]:
np.median(v)

2.0

In [19]:
np.percentile(big_array, q=50)

0.500067896744686

In [20]:
np.median(big_array)

0.500067896744686

In [21]:
np.percentile(big_array, q=100)

0.9999991427901321

In [22]:
np.max(big_array)

0.9999991427901321

In [23]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

5.374707023886316e-08
0.24994660037626584
0.500067896744686
0.7503259264706631
0.9999991427901321


In [24]:
np.var(big_array)

0.083408226209712

In [25]:
np.std(big_array)

0.28880482372999244

In [26]:
x = np.random.normal(0, 1, 1000000)

In [27]:
np.mean(x)

0.0013739286161491412

In [28]:
np.std(x)

0.9993452884264948