# 09-Arg-Operation-in-Numpy

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, 1000000)

## Index

In [3]:
np.argmin(x) # where is the min?

262898

In [4]:
x[315473]

0.8139446933604418

In [5]:
np.min(x)

-5.129925144454014

In [6]:
np.argmax(x)

132455

In [7]:
x[885414]

-0.6297274234745553

In [8]:
np.max(x)

4.806371749033755

## index and sort

In [9]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
np.random.shuffle(x)
x

array([ 8,  1,  9,  0, 10, 14,  5,  3,  4,  6,  2, 12, 13, 11, 15,  7])

In [11]:
np.sort(x) # does not change original x 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
x

array([ 8,  1,  9,  0, 10, 14,  5,  3,  4,  6,  2, 12, 13, 11, 15,  7])

In [13]:
x.sort()

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
X = np.random.randint(10, size=(4,4))
X

array([[9, 5, 6, 5],
       [5, 3, 6, 4],
       [8, 0, 0, 6],
       [0, 6, 3, 4]])

In [16]:
np.sort(X, axis=0) #column wise

array([[0, 0, 0, 4],
       [5, 3, 3, 4],
       [8, 5, 6, 5],
       [9, 6, 6, 6]])

In [17]:
np.sort(X, axis=1) # row wise

array([[5, 5, 6, 9],
       [3, 4, 5, 6],
       [0, 0, 6, 8],
       [0, 3, 4, 6]])

### use index

In [18]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
np.random.shuffle(x)

In [20]:
x

array([ 9, 13, 10,  6,  3,  8, 15,  4,  1, 11,  5, 12,  7, 14,  0,  2])

In [21]:
np.argsort(x)

array([14,  8, 15,  4,  7, 10,  3, 12,  5,  0,  2,  9, 11,  1, 13,  6])

In [22]:
np.partition(x, 3) # left is smaller than 3, right is bigger than 3

array([ 0,  1,  2,  3,  4,  8, 15, 13,  6, 11,  5, 12,  7, 14, 10,  9])

In [23]:
np.argpartition(x, 3)

array([14,  8, 15,  4,  7,  5,  6,  1,  3,  9, 10, 11, 12, 13,  2,  0])

In [24]:
X

array([[9, 5, 6, 5],
       [5, 3, 6, 4],
       [8, 0, 0, 6],
       [0, 6, 3, 4]])

In [25]:
np.argsort(X, axis=1) #row wise

array([[1, 3, 2, 0],
       [1, 3, 0, 2],
       [1, 2, 3, 0],
       [0, 2, 3, 1]])

In [26]:
np.argpartition(X, 2, axis=1) 

array([[1, 3, 2, 0],
       [1, 3, 0, 2],
       [1, 2, 3, 0],
       [0, 2, 3, 1]])